### ISSUE TITLE
posthtml is not working (discovered in Linux)

### ISSUE THREAD

**Issue by awikkerink** [Brightspace/brightspace-integration#400]
In posthtml-cli, the error was not being caught. node v7 realized this by showing an uncaught rejected promise. Here is the error from posthtml-cli:
```
TypeError: Cannot read property 'minifier' of undefined
    at /home/awikkerink/dev/brightspace-integration/node_modules/deepmerge/index.js:50:55
    at Array.forEach (native)
    at mergeObject (/home/awikkerink/dev/brightspace-integration/node_modules/deepmerge/index.js:49:25)
    at deepmerge (/home/awikkerink/dev/brightspace-integration/node_modules/deepmerge/index.js:67:16)
    at /home/awikkerink/dev/brightspace-integration/node_modules/post-load-plugins/node_modules/post-config/lib/modules.js:2:1375
    at Array.forEach (native)
    at /home/awikkerink/dev/brightspace-integration/node_modules/post-load-plugins/node_modules/post-config/lib/modules.js:2:934
    at Array.forEach (native)
    at _class.configExtends (/home/awikkerink/dev/brightspace-integration/node_modules/post-load-plugins/node_modules/post-config/lib/modules.js:2:418)
    at exports.default (/home/awikkerink/dev/brightspace-integration/node_modules/post-load-plugins/node_modules/post-config/lib/index.js:1:624)
```

It appears to be looking for `html` and `posthtml` properties from package.json.

**Comment by awikkerink** [comment]
ping @dlockhart

**Comment by dlockhart** [comment]
@awikkerink Interesting... posthtml is definitely running for me on Node version `5.8.0`, which is what Travis is set up to use. I'll try to investigate at some point.

**Comment by awikkerink** [comment]
https://s.brightspace.com/lib/bsi/10.6.11-daylight.1/bsi.html is not minified
